apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-frontend-deployment
  namespace: trendify
  labels:
    app: ecommerce-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-frontend
  template:
    metadata:
      labels:
        app: ecommerce-frontend
    spec:
      containers:
      - name: ecommerce-frontend
        image: onkar1817/trendify-ecommerce-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80

        resources:
          requests: # minimum resource requirement
            cpu: 100m
            memory: 128Mi

          limits: # maximum resource requirement
            cpu: 250m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80

        readinessProbe:
          httpGet:
            path: /
            port: 80
